# Generated by Django 6.0.4 on 2026-04-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('elevation', models.IntegerField(blank=True, help_text='Nadmořská výška v metrech', null=True)),
                ('orientation', models.CharField(blank=True, choices=[('N', 'Sever'), ('NE', 'Severovýchod'), ('E', 'Východ'), ('SE', 'Jihovýchod'), ('S', 'Jih'), ('SW', 'Jihozápad'), ('W', 'Západ'), ('NW', 'Severozápad')], max_length=2)),
                ('terrain', models.CharField(blank=True, choices=[('forest', 'Les'), ('meadow', 'Louka'), ('rocky', 'Skalnatý terén'), ('mixed', 'Smíšený')], max_length=20)),
                ('water_nearby', models.BooleanField(default=False, help_text='Je poblíž zdroj vody?')),
                ('water_distance', models.IntegerField(blank=True, help_text='Vzdálenost od vody v metrech', null=True)),
                ('wind_exposure', models.IntegerField(blank=True, help_text='Expozice větru 1-5 (1=chráněné, 5=velmi exponované)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
    ]
