# Generated by Django 6.0.4 on 2026-04-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='shelter_distance',
            field=models.IntegerField(blank=True, help_text='Vzdálenost od přístřešku v metrech', null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='shelter_nearby',
            field=models.BooleanField(default=False, help_text='Je poblíž přístřešek?'),
        ),
    ]
